[package]
name = "chomper"
version = "0.3.0"
authors = ["Nathan Mills <38995150+Quipyowert2@users.noreply.github.com>"]
[dependencies]
rand = "0.8.5"
[dependencies.sdl2]
version = "0.35.0"
default-features = false
features = ["ttf"]